name: Angular Build Check

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch: {}

jobs:
  build-webapp:
    name: Build Angular Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24  # or match your local version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build